const products = [
  {
    name: "Cheese Burguer",
    price: 14.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kqXN4V8x/200/200/original?country=br",
    category: "carne",
    id: 1,
  },
  {
    name: "Quarteirão com Queijo",
    price: 15.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kfXDlz7u/200/200/original?country=br",
    category: "carne",
    id: 2,
  },
  {
    name: "Cheddar McMelt",
    price: 11.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kzXv7hw4/200/200/original?country=br",
    category: "carne",
    id: 3,
  },
  {
    name: "Duplo Quarteirão",
    price: 12.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kzX1Xu4q/200/200/original?country=br",
    category: "carne",
    id: 4,
  },
  {
    name: "Duplo Burguer Bacon",
    price: 11.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kMX5kx4H/200/200/original?country=br",
    category: "carne",
    id: 5,
  },
  {
    name: "Duplo Cheddar",
    price: 20.99,
    img: "https://salvadornorteonline.com.br/salvadornorteonline/2020/09/Duplo-Cheddar.jpg",
    category: "carne",
    id: 6,
  },
  {
    name: "Bacon Burguer",
    price: 14.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGIiGU3D-N7UA7LT0HIQwmopH9VrPpX0zoD0T1xTTTuJDkv75zyETjN7DYQlt7kvnbNsE&usqp=CAU",
    category: "carne",
    id: 7,
  },
  {
    name: "Big Cheddar",
    price: 24.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYUgNJJnlQt6rYezbnZ_v1y6zxDOUsnBHYl68ih8Qb5lYSAXqT3KKMs-7XqhtdawBf6_Q&usqp=CAU",
    category: "carne",
    id: 8,
  },
  {
    name: "Combo BigMac",
    price: 30.99,
    img: "https://www.prischew.com/wp-content/uploads/BigMac-EVM_1a.jpg",
    category: "combo",
    id: 9,
  },
  {
    name: "Batata Pequena",
    price: 6.99,
    img: "https://www.imagensempng.com.br/wp-content/uploads/2021/08/04-41.png",
    category: "acompanhamento",
    id: 10,
  },
  {
    name: "Batata Grande",
    price: 12.99,
    img: "https://static.wixstatic.com/media/d811f7_6da59c9031fd446890bee0d9c8d86fde~mv2.png/v1/fill/w_460,h_326,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/batata%20frita1.png",
    category: "acompanhamento",
    id: 11,
  },
  {
    name: "Batata com Cheddar",
    price: 16.99,
    img: "https://imagensemoldes.com.br/wp-content/uploads/2020/04/Batata-Frita-Cheddar-e-Bacon-PNG.png",
    category: "acompanhamento",
    id: 12,
  },
  {
    name: "Coca Cola",
    price: 4.99,
    img: "https://trimais.vteximg.com.br/arquivos/ids/1019734-1000-1000/foto_original.jpg?v=637484813420070000",
    category: "acompanhamento",
    id: 13,
  },
  {
    name: "Onion Rings",
    price: 10.99,
    img: "https://i.pinimg.com/originals/06/d4/82/06d4821cfff3c500532b3c24c588b3b6.png",
    category: "acompanhamento",
    id: 14,
  },
  {
    name: "Fanta",
    price: 4.99,
    img: "http://d2r9epyceweg5n.cloudfront.net/stores/001/043/122/products/fanta-3501-f2e0836be024d42fc915698485225379-640-0.png",
    category: "acompanhamento",
    id: 15,
  },
  {
    name: "Sundae Chocolate",
    price: 4.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXuLeTy/200/200/original?country=br",
    category: "sobremesa",
    id: 16,
  },
  {
    name: "Sundae Morango",
    price: 4.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXNtbWx/200/200/original?country=br",
    category: "sobremesa",
    id: 17,
  },
  {
    name: "Sundae Caramelo",
    price: 4.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXJ6Wzq/200/200/original?country=br",
    category: "sobremesa",
    id: 18,
  },
  {
    name: "McFlurry Ovomaltine",
    price: 10.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXU0kng/200/200/original?country=br",
    category: "sobremesa",
    id: 19,
  },
  {
    name: "McShake Kopenhagem",
    price: 14.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXhmkwl/200/200/original?country=br",
    category: "sobremesa",
    id: 20,
  },
  {
    name: "McShake Morango",
    price: 14.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXm9ThH/200/200/original?country=br",
    category: "sobremesa",
    id: 21,
  },
  {
    name: "McShake Ovomaltine",
    price: 14.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXA6qBU/200/200/original?country=br",
    category: "sobremesa",
    id: 22,
  },
  {
    name: "Caldo&Fredo Maçã",
    price: 14.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$ktXXFMqv/200/200/original?country=br",
    category: "sobremesa",
    id: 23,
  },
  {
    name: "Caldo&Fredo Chocolate",
    price: 14.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$ktXsZlyN/200/200/original?country=br",
    category: "sobremesa",
    id: 24,
  },
  {
    name: "Caldo&Fredo Caramelo",
    price: 14.99,
    img: "https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$ktXatkPE/200/200/original?country=br",
    category: "sobremesa",
    id: 25,
  },
];

export default products;
